// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtw8R2iK1BcUrS1Sy5E7CuqNkMNJSARzY',
    appId: '1:630435776416:android:151c1870b537a6796d06c5',
    messagingSenderId: '630435776416',
    projectId: 'daily2kart-6c635',
    storageBucket: 'daily2kart-6c635.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSJwxtL5dRpozP1sdrZTPxchKaL93DZeE',
    appId: '1:630435776416:ios:770b95088c50cdd86d06c5',
    messagingSenderId: '630435776416',
    projectId: 'daily2kart-6c635',
    storageBucket: 'daily2kart-6c635.firebasestorage.app',
    iosBundleId: 'daily2kart',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYJCmFXLRVXu3v6MwM1NymZOmeZ1iSgc4',
    appId: '1:630435776416:web:008d495a2eff56e06d06c5',
    messagingSenderId: '630435776416',
    projectId: 'daily2kart-6c635',
    authDomain: 'daily2kart-6c635.firebaseapp.com',
    storageBucket: 'daily2kart-6c635.firebasestorage.app',
    measurementId: 'G-VBYL1CB69N',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSJwxtL5dRpozP1sdrZTPxchKaL93DZeE',
    appId: '1:630435776416:ios:ca8dd08fabec8e386d06c5',
    messagingSenderId: '630435776416',
    projectId: 'daily2kart-6c635',
    storageBucket: 'daily2kart-6c635.firebasestorage.app',
    iosBundleId: 'com.wrteam.eshop.pro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYJCmFXLRVXu3v6MwM1NymZOmeZ1iSgc4',
    appId: '1:630435776416:web:6791426935ea604f6d06c5',
    messagingSenderId: '630435776416',
    projectId: 'daily2kart-6c635',
    authDomain: 'daily2kart-6c635.firebaseapp.com',
    storageBucket: 'daily2kart-6c635.firebasestorage.app',
    measurementId: 'G-99SMVHSMC0',
  );

}